- .babelrc
- .travis.yml
- package.json
- src/index.js
- yarn.lock
Fixes #1 
This PR also drops support for Node 4, we can consider supporting it if it is ever needed.
> Remove babel-polyfill and drop support for Node 4

- package.json
- yarn.lock
For some unknown reason `eslint` was pinned to v4.5.0, but since the tests are running fine with the latest release we should lift that constraint.
> Use caret constraint for `eslint` dependency

- README.md
- integrationTests/__fixtures__/format/__eslint__/file.js
- integrationTests/__fixtures__/format/jest-runner-eslint.config.js
- integrationTests/__fixtures__/format/jest.config.js
- integrationTests/__snapshots__/format.test.js.snap
- integrationTests/format.test.js
- src/runESLint.js
- src/utils/normalizeConfig.js
Allows passing a [custom formatter](https://eslint.org/docs/user-guide/formatters/) to ESLint.
> Add format to cliOptions

- src/runESLint.js
Jest allows for an option called `setupTestFrameworkScriptFile` that is defined
as a path to a module that is run before each of your test files. This commit
adds similar support to jest-runner-eslint.
This implementation will only actually run the setupTestFrameworkScriptFile one
time, since this runner executes the tests in persistent workers instead of
isolated vms.
We're working on some internal tooling that we hope can server as an abstracted eslint, and we're hoping to use this tool.  We're running into some issues though as the tool assumes that eslint will be installed in our app, and we'd rather use it as a dependency of our tool.
An alternative to this approach would be to expand the configuration of this tool to allow us to point to our preferred eslint install. Let me know if …
> Add support for setupTestFrameworkScriptFile option.

- README.md
- src/utils/__tests__/normalizeConfig.test.js
- src/utils/normalizeConfig.js
Fixes: https://github.com/jest-community/jest-runner-eslint/issues/27#issuecomment-375263725
In the [ESLint docs for the CLIEngine](https://eslint.org/docs/developer-guide/nodejs-api#cliengine) clearly states that `rules` is a JSON object and not an array of strings.
The "string" version (e.g. `--rule "quotes: [2, double]"`) is only used by the CLI. When the args are parsed, the `rule` is also a JSON object.
In the case of this library, the `jest-runner-eslint.config.js` is a js file, so we can pass an object directly.
```js
module.exports = {
cliOptions: {
format: 'node_modules/eslint-formatter-pretty',
rules: {
'import/no-unresolved': 2,
'prettier/prettier': [
'error',
{ trailingComma: 'es5', singleQuote: true },
],
},
},
};
```
Now ESLint properly receives the additional rules.
> fix(cli-options): rules should be passed as an object instead of array of strings

- README.md
- integrationTests/__fixtures__/loud/.eslintrc.json
- integrationTests/__fixtures__/loud/__eslint__/file.js
- integrationTests/__fixtures__/loud/jest-runner-eslint.config.js
- integrationTests/__fixtures__/loud/jest.config.js
- integrationTests/__fixtures__/max-warnings/.eslintrc.json
- integrationTests/__fixtures__/max-warnings/__eslint__/file.js
- integrationTests/__fixtures__/max-warnings/__eslint__/file2.js
- integrationTests/__fixtures__/max-warnings/jest-runner-eslint.config.js
- integrationTests/__fixtures__/max-warnings/jest.config.js
- integrationTests/__snapshots__/loud.test.js.snap
- integrationTests/__snapshots__/max-warnings.test.js.snap
- integrationTests/loud.test.js
- integrationTests/max-warnings.test.js
- src/runESLint.js
- src/utils/normalizeConfig.js
This PR adds the remaining options that makes sense. I made `quiet` default to `true` so it doesn't impact the current behavior. If `false`, any warnings are output as `console.warn` messages in the test result log. The `maxWarnings` option is a little weird, since files are linted individually, whereas the actual cli option applies to warnings across all files. My use case is `maxWarnings: 0`, and that's all that I've ever seen in the wild, so I'm not sure it's that big of a deal.
> Add more options

- jest.config.js
- package.json
- src/__tests__/runESLint.test.js
- src/runESLint.js
- src/utils/__tests__/normalizeConfig.test.js
- src/utils/normalizeConfig.js
- yarn.lock
This PR is a small cleanup in runESLint.js it also adds a couple of unit tests to it. This is in preparation for the #43 which should come next
> Small clean up in runESLint and improve test setup

- .travis.yml
- README.md
- integrationTests/__snapshots__/custom-parser.test.js.snap
- integrationTests/custom-parser.test.js
- package.json
- src/utils/__tests__/normalizeConfig.test.js
- src/utils/normalizeConfig.js
- yarn.lock
This PR combines #70 and #76, then continues by resolving additional test failures and configuring Travis testing matrix across ESLint versions.
† This was done with two special techniques: 1) checking `eslint.CLIEngine.version`, 2) adding a snapshot for both versions and "skipping" the version not being tested. Both techniques have multiple alternate solutions. ex. 1) could be made to import the `package.json` file and check version there. 2) could be converted to inline snapshots. Open to alternate solutions if the current ones aren't palatable.
Closes #70
> Allow ESLint6

- README.md
Fixing this default value in the docs which doesn't match what it is in normalizeConfig.js
> chore: docs - correct default value for ‘quiet’

- README.md
- src/utils/normalizeConfig.js
Closes #94.
I did not add a test case to `normalizeConfig.test.js` as it already doesn't have test cases for every option, only for every option type to make sure the type conversions work. This is pretty declarative anyway so declaring the new option again in the test would just be repitition.
Manually tested by linking into a project that does not work without setting the option - it works now.
Could consider passing the cwd to ESLint ourselves as a default instead of relying on the ESLint default by passing `undefined` as a default. This is the first option to pass `undefined` by default. But I don't see a reason why `jest-runner-eslint` would need to take control of the default option here.
> feat(cli-options): support resolvePluginsRelativeTo

- package.json
- yarn.lock
- ESLint can't be a dependency + peerDependency
- `babel-jest` should have the same restriction like `jest` (like we do in our tests)
> fix: Fix dependencies

- integrationTests/__snapshots__/custom-parser.test.js.snap
- integrationTests/__snapshots__/failing.test.js.snap
- integrationTests/__snapshots__/format.test.js.snap
- integrationTests/__snapshots__/max-warnings.test.js.snap
- package.json
- src/utils/getESLintOptions.js
- src/watchFixPlugin/__tests__/index.test.js
- yarn.lock
These should all still support Node 8. Output of `yarn outdated` on this branch:
All of those versions drop node 8.
(I'm not 100% sure about the snapshot changes, let's see what CI says).
EDIT: Snaps seems to be correct, nice
also nice 🎉
> chore: upgrade dependencies

- integrationTests/custom-parser.test.js
`CLIEngine` export is deprecated in v7 and removed in v8 of ESLint, so let's look at the ESLint package version instead.
> chore: detect version of eslint, not its engine

- .github/workflows/nodejs.yml
Needs to match the Jest version
> chore: install babel-jest as part of the CI run

- .eslintrc.json
- integrationTests/__fixtures__/passing/jest-runner-eslint.config.js
- package.json
- src/runner/__tests__/runESLint.test.js
- src/runner/runESLint.js
- src/utils/__tests__/normalizeConfig.test.js
- src/utils/getESLintOptions.js
- src/utils/normalizeConfig.js
- yarn.lock
BREAKING CHANGE: Using `ESLint` might need different configuration
options. See https://eslint.org/docs/developer-guide/nodejs-api#parameters
`CLIEngine` is deprecated in ESLint v7 and removed entirely in ESLint v8, replaced by `ESLint`.
Landing this might give us support for ESLint v8 (#123) without changing anything more (although peer dep might still warn)
> feat: use `ESLint` instead of `CLIEngine` when available

- README.md
Link to `projects` section on Jest docs doesn't work.
Fix the link to the correct URL.
> docs: correct link to "projects" Jest documentation

- package.json
> deps: allow babel-jest v28

- .github/workflows/nodejs.yml
- package.json
v1+ is not compatible with Jest 27 and earlier.
See discussion: https://github.com/jest-community/jest-runner-eslint/pull/135#discussion_r863513145
> Allow jest-watch-typeahead ^0.6.4

- .eslintrc.json
- .github/workflows/nodejs.yml
- package.json
- yarn.lock
This drops support for Node v10, ESLint v6 and Jest 25&26.
This PR also explicitly does not support Node 13, 15 or 17, neither if which we have ever tested against on CI.
I'm still keeping Node 12 around, even though it's been EOL for almost a year. This isn't as onerous as Node 10, so I think it's a fine middle ground.
---
This allows us to greatly update our dependencies - specifically `create-jest-runner` which has long been requested.
Closes #121
> feat: upgrade old dependencies

- src/runner/__tests__/runESLint.test.js
- src/runner/runESLint.js
- src/utils/__tests__/normalizeConfig.test.js
- src/utils/getESLintOptions.js
- src/utils/normalizeConfig.js
It looks like the `CLIEngine` code is a vestige of older versions of eslint that this library no longer supports.
Removing that code significantly simplifies the library and will result in a pretty big simplification to https://github.com/jest-community/jest-runner-eslint/pull/176 as well.
> Remove cliengine code

- .github/workflows/nodejs.yml
- integrationTests/__fixtures__/flat-config/__eslint__/file.js
- integrationTests/__fixtures__/flat-config/eslint.config.js
- integrationTests/__fixtures__/flat-config/jest.config.js
- integrationTests/__fixtures__/legacy-config-at-eslint.config.js/__eslint__/file.js
- integrationTests/__fixtures__/legacy-config-at-eslint.config.js/eslint.config.js
- integrationTests/__fixtures__/legacy-config-at-eslint.config.js/jest-runner-eslint.config.js
- integrationTests/__fixtures__/legacy-config-at-eslint.config.js/jest.config.js
- integrationTests/__snapshots__/flat-config.test.js.snap
- integrationTests/__snapshots__/legacy-config-at-eslint.config.js.test.js.snap
- integrationTests/flat-config.test.js
- integrationTests/legacy-config-at-eslint.config.js.test.js
- src/runner/runESLint.js
Fixes #166 .
Note I also had to change the strategy for running integration tests is this PR.  Prior to this PR, integration tests ran in a child process where the cwd was the root of the integration tests, and jest projects were used to select individual integration test directories.  However, [eslint will look for the flat config starting in the process cwd](https://github.com/eslint/eslint/blob/d85efad655deacc0dc3fdbbace33307094c3b91b/lib/cli.js#L299), so with that strategy the flat config would have to be placed in a common path to all integration tests, and thus the integration test runs would always detect that they're running in flat config mode.
As of this PR, the integration tests run with a child process where the cwd is the individual integration test fixture path as well. …
> Support eslint's new flat config

- src/runner/__tests__/runESLint.test.js
- src/runner/runESLint.js
Hi !
I have fixed [issue 58](https://github.com/jest-community/jest-runner-eslint/issues/58).
I just got it to work for now, so if you have any comments, please comment!
> Fix issue #58 cliOptions.fix is ignored

- src/runner/runESLint.js
Fixes #204.
Jest appears to have changed the format of `TestResult`. What was `perfStats.duration` is now `perfStats.runtime`:
https://github.com/jestjs/jest/blob/edeecfae240bfd54b33f3c9eae156bd157447e5a/packages/jest-test-result/src/types.ts#L90-L122
Adding `runtime` property solves the problem.
I've left the `duration` property in place too in case that provides compatibility with older versions of Jest.
> Fix reporting test durations

- integrationTests/__fixtures__/quiet-mode/.eslintrc.json
- integrationTests/__fixtures__/quiet-mode/__eslint__/file.js
- integrationTests/__fixtures__/quiet-mode/jest-runner-eslint.config.js
- integrationTests/__fixtures__/quiet-mode/jest.config.js
- integrationTests/__snapshots__/quiet-mode.test.js.snap
- integrationTests/quiet-mode.test.js
- src/runner/runESLint.js
Hello!
This PR addresses issue #211 
When the `quiet` cliOption is passed the call to ESLint's `getErrorResults` filters out warnings, which is expected. Prior to this PR we were using the full list of errors + warnings from ESLint to report the assertions, which incorrectly logged out warnings as error. This PR uses the filtered list instead if `cliOptions.quiet` is specified.
I tested this locally to make sure that it's working as expected, and also verified that the integration test also does not show the warnings.
> Do not report warnings as errors in quiet mode

- .github/workflows/nodejs.yml
- src/utils/normalizeConfig.js
Node 18.19 backported whatever v8 change that breaks fake timers in Jest 28, so we need to skip that combo on CI
> chore: skip tests with Jest 28 and Node 18

- .github/workflows/nodejs.yml
- src/runner/runESLint.js
- src/utils/__tests__/normalizeConfig.test.js
- src/utils/getESLintOptions.js
- src/utils/normalizeConfig.js
- yarn.lock
This PR implements updates the eslint dependency to 8.57.0 and fixes the error `'reportUnusedDisableDirectives' has been removed. Please use the 'overrideConfig.linterOptions.reportUnusedDisableDirectives' option instead.`.
In doing this, I also made the following improvements:
1. use the new [`loadESLint`](https://eslint.org/docs/latest/integrate/nodejs-api#loadeslint) function to load `ESLint` or `FlatESLint`, rather than using our own logic
2. refactors the `normalizeConfig.js` file to have explicit separate config shapes for the legacy config and the flat config.  This also removes the need to have the code to deal with invalid config variables that we had [here](https://github.com/jest-community/jest-runner-eslint/blob/25a7d38b81c6618230f1f4c5153d639ab8aede08/src/runner/runESLint.js#L …
> fix: implement fixes to work with eslint 8.57.0

- src/runner/__tests__/runESLint.test.js
- src/runner/runESLint.js
Fixes https://github.com/jest-community/jest-runner-eslint/issues/258
> Fix reported location

- .eslintrc.json
- src/utils/__tests__/normalizeConfig.test.js
This alias has been removed in Jest v30
> test: use `toThrow` instead of `toThrowError`
